package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, minimum-scale=1.0, maximum-scale=1.0\">\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("<script src=\"//html5shiv.googlecode.com/svn/trunk/html5.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("\r\n");
      out.write("<!-- END OF DON'T TOUCH -->\r\n");
      out.write("\r\n");
      out.write("<!-- Website Title -->\r\n");
      out.write("<title>Product Launch</title>\r\n");
      out.write("<!-- END OF Website Title -->\r\n");
      out.write("\r\n");
      out.write("<!--  Website description - Change the 'content' section to whatever you want -->\r\n");
      out.write("<meta name=\"description\" content=\"Replace this text with a summary of your website. i.e. John Smith - Web Developer and Photographer - Welcome to my portfolio website! Here you will find all of my latest work. Enjoy!\">\r\n");
      out.write("<!-- END OF Website description -->\r\n");
      out.write("\r\n");
      out.write("<!-- DON'T TOUCH THIS SECTION -->\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Lato:300,400,700|Cookie' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"scripts/jquery.carouFredSel-5.5.2.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/jquery.easing.1.3.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/jquery.form.js\"></script> \r\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/scripts.js\"></script> \r\n");
      out.write("</head>\r\n");
      out.write("<!-- END OF DON'T TOUCH -->\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("\t<div id=\"top\">\r\n");
      out.write("        <div id=\"logo\">\r\n");
      out.write("          <img src=\"images/logo.png\" alt=\"logo\" width=\"118\" height=\"139\" id=\"logoimage\">\t<!-- Logo image -->\r\n");
      out.write("            <h1 id=\"logotitle\">Product Launch App...</h1>\t\r\n");
      out.write("            <!-- Logo text -->\r\n");
      out.write("        </div><!--/logo-->\r\n");
      out.write("    \r\n");
      out.write("        <nav>\t<!-- Navigation Start -->\r\n");
      out.write("            <ul>\r\n");
      out.write("            \t<li><a href=\"#top\">HOME</a></li>\r\n");
      out.write("                <li><a href=\"#about\">About</a></li>\r\n");
      out.write("                <li><a href=\"#work\">Work</a></li>\r\n");
      out.write("                <li><a href=\"#footer\">Contact</a></li>\r\n");
      out.write("        \r\n");
      out.write("            </ul>      \r\n");
      out.write("        </nav>\t<!-- Navigation End -->\r\n");
      out.write("       \r\n");
      out.write("    \r\n");
      out.write("    </div><!--/top-->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <hr/><!-- Horizontal Line -->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("  <section id=\"slideshow\">\t<!-- Slideshow Start -->\r\n");
      out.write("        <div class=\"html_carousel\">\r\n");
      out.write("\t\t\t<div id=\"slider\">\r\n");
      out.write("            \r\n");
      out.write("\t\t\t\t<div class=\"slide\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/slideshow/sliderimage1.jpg\" width=\"3000\" height=\"783\" alt=\"image 1\"/><!-- Replace these images with your own but make sure they are 3000px wide and 783px high or the same ration -->\r\n");
      out.write("\t\t\t\t</div><!--/slide-->\r\n");
      out.write("                \r\n");
      out.write("\t\t\t\t<div class=\"slide\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/slideshow/sliderimage2.jpg\" width=\"3000\" height=\"783\" alt=\"image 2\"/><!-- Replace these images with your own but make sure they are 3000px wide and 783px high or the same ration -->\r\n");
      out.write("\t\t\t\t</div><!--/slide-->\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"slide\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/slideshow/sliderimage3.jpg\" width=\"3000\" height=\"783\" alt=\"image 3\"/><!-- Replace these images with your own but make sure they are 3000px wide and 783px high or the same ration -->\r\n");
      out.write("\t\t\t\t</div><!--/slide-->\r\n");
      out.write("                \r\n");
      out.write("\t\t\t</div><!--/slider-->\r\n");
      out.write("\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t</div><!--/html_carousel-->\r\n");
      out.write("    </section>\t<!-- Slideshow End -->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("<!-- TO MAKE THE PHP FORM WORK, ALL YOU NEED TO DO IS OPEN UP THE FILE CALLED 'submitemail.php' AND CHANGE WHERE IT SAYS 'your email goes here' -->\r\n");
      out.write("\r\n");
      out.write("<!-- DON'T TOUCH THIS SECTION -->\r\n");
      out.write("\r\n");
      out.write("<footer id=\"footer\">\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("    \t<section class=\"left\">\r\n");
      out.write("    \t<h4>Enter Specification </h4>\r\n");
      out.write("            <div  id=\"formwrap\">\r\n");
      out.write("                <form method=\"post\" id=\"submitform2\" action=\"home\">\r\n");
      out.write("<table border=\"3\" width=800>\r\n");
      out.write("<tr><td><font color='white'>Company Name :   </td> <td><select name=\"cname\">\r\n");
      out.write("\t\t\t\t<option value=\"0\"> Select </option>\r\n");
      out.write("\t\t\t\t<option value=\"Samsung\">Samsung </option>\r\n");
      out.write("\t\t\t\t<option value=\"Apple\">Apple</option>\r\n");
      out.write("\t\t\t\t<option value=\"Acer\">Acer </option>\r\n");
      out.write("\t\t\t\t<option value=\"Toshiba\">Toshiba </option>\r\n");
      out.write("\t\t\t\t<option value=\"Asus\">Asus </option>\r\n");
      out.write("\t\t\t\t<option value=\"Lenovo\">Lenovo </option>\r\n");
      out.write("\t\t\t\t<option value=\"Micromax\">Micromax </option>\r\n");
      out.write("\t\t\t\t<option value=\"HCL\">HCL </option>\r\n");
      out.write("\t\t\t\t<option value=\"Amazon\">Amazon </option>\r\n");
      out.write("\t\t\t\t<option value=\"Sony\">Sony </option>\r\n");
      out.write("\t\t\t\t<option value=\"HP\">HP </option>\r\n");
      out.write("\t\t\t\t<option value=\"HTC\">HTC </option>\r\n");
      out.write("\t\t\t\t<option value=\"Huawei\">Huawei </option>\r\n");
      out.write("\t\t\t\t<option value=\"Google\">Google </option>\r\n");
      out.write("\t\t\t\t<option value=\"LG\">LG </option>\r\n");
      out.write("\t\t\t\t<option value=\"Blackberry\">Blackberry </option>\r\n");
      out.write("\t\t\t\t<option value=\"Dell\">Dell </option>\r\n");
      out.write("\t\t\t\t<option value=\"Others\">Others </option>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</select></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\r\n");
      out.write("<td> <font color='white'>Product Name : </td> <td> <input type=\"text\" name=\"pname\" /> </td> \r\n");
      out.write("\r\n");
      out.write("<td> <font color='white'>Processor Frequency(in GHz) : </td> <td> <input type = \"text\" name = \"pf\" /> </td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td><font color='white'>Processor Core :   </td> <td> <select name=\"pc\">\r\n");
      out.write("\t\t\t\t<option value=\"0\"> Select </option>\r\n");
      out.write("\t\t\t\t<option value=\"1\">1 </option>\r\n");
      out.write("\t\t\t\t<option value=\"2\">2 </option>\r\n");
      out.write("\t\t\t\t<option value=\"4\">4</option>\r\n");
      out.write("\t\t\t\t<option value=\"8\">8 </option>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("</select> </td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<td><font color='white'>Processor Company :   </td> <td> <select name=\"pq\">\r\n");
      out.write("\t\t\t\t<option value=\"0\"> Select </option>\r\n");
      out.write("\t\t\t\t<option value=\"50\">Intel </option>\r\n");
      out.write("\t\t\t\t<option value=\"45\">Apple</option>\r\n");
      out.write("\t\t\t\t<option value=\"43\">Qualcomm </option>\r\n");
      out.write("\t\t\t\t<option value=\"41\">Nvidia </option>\r\n");
      out.write("\t\t\t\t<option value=\"39\">Exynox </option>\r\n");
      out.write("\t\t\t\t<option value=\"36\">Ti Omap </option>\r\n");
      out.write("\t\t\t\t<option value=\"ot\">Others </option>\r\n");
      out.write("</select> </td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td><font color='white'>Mac Support :   </td> <td> <select name=\"ms\">\r\n");
      out.write("\t\t\t\t<option value=\"0\"> Select </option>\r\n");
      out.write("\t\t\t\t<option value=\"1\">Yes </option>\r\n");
      out.write("\t\t\t\t<option value=\"0\">No</option>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("</select> </td>\r\n");
      out.write("<td><font color='white'>Android Support :   </td> <td> <select name=\"as\">\r\n");
      out.write("\t\t\t\t<option value=\"0\"> Select </option>\r\n");
      out.write("\t\t\t\t<option value=\"1\">Yes </option>\r\n");
      out.write("\t\t\t\t<option value=\"0\">No</option>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("</select> </td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td><font color='white'>Windows Support :   </td> <td> <select name=\"ws\">\r\n");
      out.write("\t\t\t\t<option value=\"0\"> Select </option>\r\n");
      out.write("\t\t\t\t<option value=\"1\">Yes </option>\r\n");
      out.write("\t\t\t\t<option value=\"0\">No</option>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("</select> </td>\r\n");
      out.write("<td><font color='white'>Blackberry Support :   </td> <td> <select name=\"bs\">\r\n");
      out.write("\t\t\t\t<option value=\"0\"> Select </option>\r\n");
      out.write("\t\t\t\t<option value=\"1\">Yes </option>\r\n");
      out.write("\t\t\t\t<option value=\"0\">No</option>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("</select> </td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td><font color='white'>Display Size(in inches)\t:   </td> <td> <input type = \"text\" name = \"ds\" /></td>\r\n");
      out.write("<td><font color='white'>Display Quality :   </td> <td> <select name=\"dq\">\r\n");
      out.write("\t\t\t\t<option value=\"0\"> Select </option>\r\n");
      out.write("\t\t\t\t<option value=\"1\">LCD </option>\r\n");
      out.write("\t\t\t\t<option value=\"2\">TFT LCD</option>\r\n");
      out.write("\t\t\t\t<option value=\"3\">HD LCD</option>\r\n");
      out.write("\t\t\t\t<option value=\"3.5\">IPS LCD</option>\r\n");
      out.write("\t\t\t\t<option value=\"4\">Full HD LCD</option>\r\n");
      out.write("\t\t\t\t<option value=\"5\">3D LCD</option>\r\n");
      out.write("\t\t\t\t<option value=\"6\">LED</option>\r\n");
      out.write("\t\t\t\t<option value=\"6.5\">IPD LED</option>\r\n");
      out.write("\t\t\t\t<option value=\"7\">LED backlit 132 PPi</option>\r\n");
      out.write("\t\t\t\t<option value=\"8\">LED backlit 264 PPi</option>\r\n");
      out.write("\t\t\t\t<option value=\"9\">HD LED</option>\r\n");
      out.write("\t\t\t\t<option value=\"10\">FULL HD LED</option>\r\n");
      out.write("\t\t\t\t<option value=\"11\">3D HD LED</option>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("</select> </td>\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("<tr></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<tr></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td><font color='white'>Display Resolution\t:   </td> <td> <input type = \"text\" name = \"dsr\" /></td>\r\n");
      out.write("<td><font color='white'>RAM(MB)\t:   </td> <td> <input type = \"text\" name = \"ram\" /></td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr><td></td><td><font color='Red'>e.g:-<br> 786X432 =786432</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td><font color='white'>Ram Type :   </td> <td> <select name=\"rt\">\r\n");
      out.write("\t\t\t\t<option value=\"0\"> Select </option>\r\n");
      out.write("\t\t\t\t<option value=\"1\">DDR1 </option>\r\n");
      out.write("\t\t\t\t<option value=\"2\">DDR2</option>\r\n");
      out.write("\t\t\t\t<option value=\"3\">DDR3</option>\r\n");
      out.write("</select> </td>\r\n");
      out.write("<td><font color='white'>On Board Memory(GB) :   </td> <td> <select name=\"obm\">\r\n");
      out.write("\t\t\t\t<option value=\"0\"> Select </option>\r\n");
      out.write("\t\t\t\t<option value=\"8\">8 </option>\r\n");
      out.write("\t\t\t\t<option value=\"16\">16 </option>\r\n");
      out.write("\t\t\t\t<option value=\"32\">32</option>\r\n");
      out.write("\t\t\t\t<option value=\"64\">64</option>\r\n");
      out.write("\t\t\t\t<option value=\"128\">128</option>\r\n");
      out.write("</select> </td>\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("<tr></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td><font color='white'>Expandable Memory :   </td> <td> <select name=\"em\">\r\n");
      out.write("\t\t\t\t<option value=\"0\"> Select </option>\r\n");
      out.write("\t\t\t\t<option value=\"0\"> 0 </option>\r\n");
      out.write("\t\t\t\t<option value=\"8\">8 </option>\r\n");
      out.write("\t\t\t\t<option value=\"16\">16 </option>\r\n");
      out.write("\t\t\t\t<option value=\"32\">32</option>\r\n");
      out.write("\t\t\t\t<option value=\"64\">64</option>\r\n");
      out.write("\t\t\t\t<option value=\"128\">128</option>\r\n");
      out.write("</select> </td>\r\n");
      out.write("<td><font color='white'>Battery Backup(Hrs)   </td> <td> <input type = \"text\" name = \"bbk\" /></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<tr></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td><font color='white'>Battery Type(mAh)   </td> <td> <input type = \"text\" name = \"bbt\" /></td>\r\n");
      out.write("<td><font color='white'>weight(in Kg.)   </td> <td> <input type = \"text\" name = \"wgt\" /></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td><font color='white'>Back Camera(MegaPixel)    </td> <td> <input type = \"text\" name = \"bcm\" /></td>\r\n");
      out.write("<td><font color='white'>Back Camera(mode)   </td> <td> <select name=\"bc\">\r\n");
      out.write("\t\t\t\t<option value=\"0\"> Select </option>\r\n");
      out.write("\t\t\t\t<option value=\"1\">VGA </option>\r\n");
      out.write("\t\t\t\t<option value=\"2\">HD</option>\r\n");
      out.write("\t\t\t\t<option value=\"3\">Full HD</option>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("</select> \r\n");
      out.write("</tr>\r\n");
      out.write("<tr></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td><font color='white'>Front Camera(MegaPixel)</td> <td> <input type = \"text\" name = \"fcm\" /></td>\r\n");
      out.write("<td><font color='white'>Front Camera(mode)   </td> <td> <select name=\"fc\">\r\n");
      out.write("\t\t\t\t<option value=\"0\"> Select </option>\r\n");
      out.write("\t\t\t\t<option value=\"1\">VGA </option>\r\n");
      out.write("\t\t\t\t<option value=\"2\">HD</option>\r\n");
      out.write("\t\t\t\t<option value=\"3\">Full HD</option>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("</select> </td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td><font color='white'>HDMI Support :   </td> <td> <select name=\"hs\">\r\n");
      out.write("\t\t\t\t<option value=\"0\"> Select </option>\r\n");
      out.write("\t\t\t\t<option value=\"1\">Yes </option>\r\n");
      out.write("\t\t\t\t<option value=\"0\">No</option>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("</select> </td>\r\n");
      out.write("<td><font color='white'>Touch Input   </td> <td> <select name=\"ti\">\r\n");
      out.write("\t\t\t\t<option value=\"0\"> Select </option>\r\n");
      out.write("\t\t\t\t<option value=\"1\">Resistive </option>\r\n");
      out.write("\t\t\t\t<option value=\"5\">Capacitive Single Touch</option>\r\n");
      out.write("\t\t\t\t<option value=\"8\">Capacitive Multi Touch 8 point</option>\r\n");
      out.write("\t\t\t\t<option value=\"10\">Capacitive Multi Touch 10 point</option>\t\t\t\t\r\n");
      out.write("</select> </td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td><font color='white'>Thickness   </td> <td> <input type = \"text\" name = \"thk\" /></td>\r\n");
      out.write("<td><font color='white'>Dimensions (Length X Breadth)inches   </td> <td> <input type = \"text\" name = \"dimn\" /></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td><font color='white'>Wifi Support:   </td> <td><select name=\"wifi\">\r\n");
      out.write("\t\t\t\t<option value=\"3\"> Select </option>\r\n");
      out.write("\t\t\t\t<option value=\"1\">Yes </option>\r\n");
      out.write("\t\t\t\t<option value=\"0\">No</option>\r\n");
      out.write("</select>\r\n");
      out.write("<td><font color='white'>Wifi type:   </td><td> <select name=\"wifiq\">\r\n");
      out.write("\t\t\t\t<option value=\"0\"> Select </option>\r\n");
      out.write("\t\t\t\t<option value=\"4\">802.11 - A/B/G/N</option>\r\n");
      out.write("\t\t\t\t<option value=\"5\">802.11 - 2 MBPS</option>\r\n");
      out.write("\t\t\t\t<option value=\"6\">802.11 - 4 MBPS</option>\r\n");
      out.write("</select>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td><font color='white'>Bluetooth Support:   </td><td> <select name=\"bts\">\r\n");
      out.write("\t\t\t\t<option value=\"3\"> Select </option>\r\n");
      out.write("\t\t\t\t<option value=\"1\">Yes </option>\r\n");
      out.write("\t\t\t\t<option value=\"0\">No</option>\r\n");
      out.write("</select>\r\n");
      out.write("<td><font color='white'>Bluetooth type:   </td><td> <select name=\"btq\">\r\n");
      out.write("\t\t\t\t<option value=\"0\"> Select </option>\r\n");
      out.write("\t\t\t\t<option value=\"2\">2</option>\r\n");
      out.write("\t\t\t\t<option value=\"2.1\">2.1</option>\r\n");
      out.write("\t\t\t\t<option value=\"3\">3</option>\r\n");
      out.write("\t\t\t\t<option value=\"4\">4</option>\r\n");
      out.write("\t\t\t\t<option value=\"5\">5</option>\r\n");
      out.write("</select>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td><font color='white'>USB Support:   </td> <td><select name=\"usbs\">\r\n");
      out.write("\t\t\t\t<option value=\"3\"> Select </option>\r\n");
      out.write("\t\t\t\t<option value=\"1\">Yes </option>\r\n");
      out.write("\t\t\t\t<option value=\"0\">No</option>\r\n");
      out.write("</select>\r\n");
      out.write("<td><font color='white'>USB type:   </td><td> <select name=\"usbq\">\r\n");
      out.write("\t\t\t\t<option value=\"0\"> Select </option>\r\n");
      out.write("\t\t\t\t<option value=\"1\">micro USB</option>\r\n");
      out.write("\t\t\t\t<option value=\"1\">usb 1.0</option>\r\n");
      out.write("\t\t\t\t<option value=\"2\">usb 2.0</option>\r\n");
      out.write("\t\t\t\t<option value=\"3\">usb 3.0</option>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("</select>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td><font color='white'>4G Support:   </td> <td><select name=\"4gs\">\r\n");
      out.write("\t\t\t\t<option value=\"3\"> Select </option>\r\n");
      out.write("\t\t\t\t<option value=\"1\">Yes </option>\r\n");
      out.write("\t\t\t\t<option value=\"0\">No</option>\r\n");
      out.write("</select>\r\n");
      out.write("\r\n");
      out.write("<td><font color='white'>3G Support:   </td> <td><select name=\"3gs\">\r\n");
      out.write("\t\t\t\t<option value=\"3\"> Select </option>\r\n");
      out.write("\t\t\t\t<option value=\"1\">Yes </option>\r\n");
      out.write("\t\t\t\t<option value=\"0\">No</option>\r\n");
      out.write("</select>\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<table width='1000'>\r\n");
      out.write("<tr height='50'></tr>\r\n");
      out.write("<tr align=\"center\"><td width='1000'>\r\n");
      out.write("\r\n");
      out.write("<input type = \"submit\" value = \"Get Price\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("     \r\n");
      out.write("             \r\n");
      out.write("\r\n");
      out.write("             \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"clearfix\"></div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<!-- SLIDESHOW SCRIPT START -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(\"#slider\").carouFredSel({\r\n");
      out.write("\tresponsive\t: true,\r\n");
      out.write("\tscroll\t\t: {\r\n");
      out.write("\t\tfx\t\t\t: \"crossfade\",\r\n");
      out.write("\t\teasing\t\t: \"swing\",\r\n");
      out.write("\t\tduration\t: 1000,\r\n");
      out.write("\t\t\r\n");
      out.write("\t},\r\n");
      out.write("\titems\t\t: {\r\n");
      out.write("\t\tvisible\t\t: 1,\r\n");
      out.write("\t\theight\t\t: \"27%\"\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- SLIDESHOW SCRIPT END -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
